### ISSUE TITLE
Prueba de issues con varias tareas

### ISSUE THREAD

**Issue by willycotes** [willycotes/coteswpslider#3]

**Comment by willycotes** [comment]
```[tasklist]
## Task list issues
- [] https://github.com/willycotes/coteswpslider/issues/4
- [] Prueba de un nuevo issues #2 


```

**Comment by willycotes** [comment]
[tasklist]
### Tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft issue title
